### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by httpgit** [SideBarEnhancements-org/SideBarEnhancements#344]
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.Stats
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 133, in reload_plugin
    obj = t()
  File "Stats in D:\Program Files\Sublime Text 3\Data\Installed Packages\SideBarEnhancements.sublime-package", line 29, in __init__
NameError: global name 'AdamTestPlugin' is not defined

**Comment by wizsilex** [comment]
I get this too.

**Comment by titoBouzout** [comment]
Nice catch, thanks!
